image: tetraweb/php
before_script:
  - apt-get update
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
stage_deploy:
  artifacts:
    paths:
    - build/
  only:
    - master
  script:
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh -p22 benftwc@benftwc.fr "/var/www_node/guestabot/update.sh"
