image: ubuntu
before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan benftwc.fr >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
Test SSH:
  script:
  - ssh benftwc@benftwc.fr
  - cd /var/www_node/guestabot
  - ./update.sh
